# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\add_data_widget.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_data_widget(object):
    def setupUi(self, add_data_widget):
        add_data_widget.setObjectName("add_data_widget")
        add_data_widget.resize(553, 490)
        self.verticalLayout = QtWidgets.QVBoxLayout(add_data_widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 9)
        self.verticalLayout.setSpacing(9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.add_non_binary_gb = QtWidgets.QGroupBox(add_data_widget)
        self.add_non_binary_gb.setCheckable(True)
        self.add_non_binary_gb.setChecked(False)
        self.add_non_binary_gb.setObjectName("add_non_binary_gb")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.add_non_binary_gb)
        self.horizontalLayout.setContentsMargins(0, 6, 0, 9)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setVerticalSpacing(0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.add_non_binary_gb)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.add_non_binary_le = QtWidgets.QLineEdit(self.add_non_binary_gb)
        self.add_non_binary_le.setObjectName("add_non_binary_le")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.add_non_binary_le)
        self.horizontalLayout.addLayout(self.formLayout)
        self.edit_non_binary_pb = QtWidgets.QPushButton(self.add_non_binary_gb)
        self.edit_non_binary_pb.setObjectName("edit_non_binary_pb")
        self.horizontalLayout.addWidget(self.edit_non_binary_pb)
        self.add_non_binary_pb = QtWidgets.QPushButton(self.add_non_binary_gb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_non_binary_pb.sizePolicy().hasHeightForWidth())
        self.add_non_binary_pb.setSizePolicy(sizePolicy)
        self.add_non_binary_pb.setObjectName("add_non_binary_pb")
        self.horizontalLayout.addWidget(self.add_non_binary_pb)
        self.verticalLayout.addWidget(self.add_non_binary_gb)
        self.add_binary_gb = QtWidgets.QGroupBox(add_data_widget)
        self.add_binary_gb.setCheckable(True)
        self.add_binary_gb.setChecked(False)
        self.add_binary_gb.setObjectName("add_binary_gb")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.add_binary_gb)
        self.horizontalLayout_2.setContentsMargins(0, 6, 0, 9)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setVerticalSpacing(0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.add_binary_le = QtWidgets.QLineEdit(self.add_binary_gb)
        self.add_binary_le.setObjectName("add_binary_le")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.add_binary_le)
        self.label_3 = QtWidgets.QLabel(self.add_binary_gb)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_2.addLayout(self.formLayout_2)
        self.edit_binary_pb = QtWidgets.QPushButton(self.add_binary_gb)
        self.edit_binary_pb.setObjectName("edit_binary_pb")
        self.horizontalLayout_2.addWidget(self.edit_binary_pb)
        self.add_binary_pb = QtWidgets.QPushButton(self.add_binary_gb)
        self.add_binary_pb.setObjectName("add_binary_pb")
        self.horizontalLayout_2.addWidget(self.add_binary_pb)
        self.verticalLayout.addWidget(self.add_binary_gb)
        self.p_cmd_gb = QtWidgets.QGroupBox(add_data_widget)
        self.p_cmd_gb.setCheckable(True)
        self.p_cmd_gb.setChecked(False)
        self.p_cmd_gb.setObjectName("p_cmd_gb")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.p_cmd_gb)
        self.horizontalLayout_3.setContentsMargins(0, 6, 0, 9)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setVerticalSpacing(0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.p_cmd_le = QtWidgets.QLineEdit(self.p_cmd_gb)
        self.p_cmd_le.setObjectName("p_cmd_le")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.p_cmd_le)
        self.p_cmd_lb = QtWidgets.QLabel(self.p_cmd_gb)
        self.p_cmd_lb.setObjectName("p_cmd_lb")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.p_cmd_lb)
        self.horizontalLayout_3.addLayout(self.formLayout_3)
        self.verticalLayout.addWidget(self.p_cmd_gb)
        self.hidden_import_gb = QtWidgets.QGroupBox(add_data_widget)
        self.hidden_import_gb.setCheckable(True)
        self.hidden_import_gb.setChecked(False)
        self.hidden_import_gb.setObjectName("hidden_import_gb")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.hidden_import_gb)
        self.horizontalLayout_4.setContentsMargins(0, 6, 0, 9)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setVerticalSpacing(0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.hidden_import_le = QtWidgets.QLineEdit(self.hidden_import_gb)
        self.hidden_import_le.setObjectName("hidden_import_le")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.hidden_import_le)
        self.hidden_import_lb = QtWidgets.QLabel(self.hidden_import_gb)
        self.hidden_import_lb.setObjectName("hidden_import_lb")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.hidden_import_lb)
        self.horizontalLayout_4.addLayout(self.formLayout_4)
        self.verticalLayout.addWidget(self.hidden_import_gb)
        self.additional_hook_gb = QtWidgets.QGroupBox(add_data_widget)
        self.additional_hook_gb.setCheckable(True)
        self.additional_hook_gb.setChecked(False)
        self.additional_hook_gb.setObjectName("additional_hook_gb")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.additional_hook_gb)
        self.horizontalLayout_5.setContentsMargins(0, 6, 0, 9)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setVerticalSpacing(0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.additional_hook_le = QtWidgets.QLineEdit(self.additional_hook_gb)
        self.additional_hook_le.setObjectName("additional_hook_le")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.additional_hook_le)
        self.additional_hook_lb = QtWidgets.QLabel(self.additional_hook_gb)
        self.additional_hook_lb.setObjectName("additional_hook_lb")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.additional_hook_lb)
        self.horizontalLayout_5.addLayout(self.formLayout_5)
        self.verticalLayout.addWidget(self.additional_hook_gb)
        self.runtime_hook_gb = QtWidgets.QGroupBox(add_data_widget)
        self.runtime_hook_gb.setCheckable(True)
        self.runtime_hook_gb.setChecked(False)
        self.runtime_hook_gb.setObjectName("runtime_hook_gb")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.runtime_hook_gb)
        self.horizontalLayout_6.setContentsMargins(0, 6, 0, 9)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setVerticalSpacing(0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.runtime_hook_le = QtWidgets.QLineEdit(self.runtime_hook_gb)
        self.runtime_hook_le.setObjectName("runtime_hook_le")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.runtime_hook_le)
        self.runtime_hook_lb = QtWidgets.QLabel(self.runtime_hook_gb)
        self.runtime_hook_lb.setObjectName("runtime_hook_lb")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.runtime_hook_lb)
        self.horizontalLayout_6.addLayout(self.formLayout_6)
        self.verticalLayout.addWidget(self.runtime_hook_gb)
        self.exclude_module_gb = QtWidgets.QGroupBox(add_data_widget)
        self.exclude_module_gb.setCheckable(True)
        self.exclude_module_gb.setChecked(False)
        self.exclude_module_gb.setObjectName("exclude_module_gb")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.exclude_module_gb)
        self.horizontalLayout_7.setContentsMargins(0, 6, 0, 9)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.formLayout_7 = QtWidgets.QFormLayout()
        self.formLayout_7.setVerticalSpacing(0)
        self.formLayout_7.setObjectName("formLayout_7")
        self.exclude_module_le = QtWidgets.QLineEdit(self.exclude_module_gb)
        self.exclude_module_le.setObjectName("exclude_module_le")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.exclude_module_le)
        self.exclude_module_lb = QtWidgets.QLabel(self.exclude_module_gb)
        self.exclude_module_lb.setObjectName("exclude_module_lb")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.exclude_module_lb)
        self.horizontalLayout_7.addLayout(self.formLayout_7)
        self.verticalLayout.addWidget(self.exclude_module_gb)
        self.encrypt_gb = QtWidgets.QGroupBox(add_data_widget)
        self.encrypt_gb.setCheckable(True)
        self.encrypt_gb.setChecked(False)
        self.encrypt_gb.setObjectName("encrypt_gb")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.encrypt_gb)
        self.horizontalLayout_8.setContentsMargins(0, 6, 0, 9)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.formLayout_8 = QtWidgets.QFormLayout()
        self.formLayout_8.setVerticalSpacing(0)
        self.formLayout_8.setObjectName("formLayout_8")
        self.encrypt_lb = QtWidgets.QLabel(self.encrypt_gb)
        self.encrypt_lb.setObjectName("encrypt_lb")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.encrypt_lb)
        self.encrypt_le = QtWidgets.QLineEdit(self.encrypt_gb)
        self.encrypt_le.setClearButtonEnabled(True)
        self.encrypt_le.setObjectName("encrypt_le")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.encrypt_le)
        self.horizontalLayout_8.addLayout(self.formLayout_8)
        self.verticalLayout.addWidget(self.encrypt_gb)

        self.retranslateUi(add_data_widget)
        QtCore.QMetaObject.connectSlotsByName(add_data_widget)

    def retranslateUi(self, add_data_widget):
        _translate = QtCore.QCoreApplication.translate
        add_data_widget.setWindowTitle(_translate("add_data_widget", "Form"))
        self.add_non_binary_gb.setTitle(_translate("add_data_widget", "添加文件/文件夹(非二进制)"))
        self.label_2.setText(_translate("add_data_widget", "路径："))
        self.add_non_binary_le.setPlaceholderText(_translate("add_data_widget", "多个路径使用分隔符隔开"))
        self.edit_non_binary_pb.setText(_translate("add_data_widget", "编辑"))
        self.add_non_binary_pb.setText(_translate("add_data_widget", "添加"))
        self.add_binary_gb.setTitle(_translate("add_data_widget", "添加二进制文件"))
        self.add_binary_le.setPlaceholderText(_translate("add_data_widget", "多个路径使用分隔符隔开"))
        self.label_3.setText(_translate("add_data_widget", "路径："))
        self.edit_binary_pb.setText(_translate("add_data_widget", "编辑"))
        self.add_binary_pb.setText(_translate("add_data_widget", "添加"))
        self.p_cmd_gb.setTitle(_translate("add_data_widget", "搜索导入路径"))
        self.p_cmd_le.setPlaceholderText(_translate("add_data_widget", "多个路径使用分隔符\":\"隔开"))
        self.p_cmd_lb.setText(_translate("add_data_widget", "路径："))
        self.hidden_import_gb.setToolTip(_translate("add_data_widget", "脚本中没有显式使用import导入的包"))
        self.hidden_import_gb.setTitle(_translate("add_data_widget", "导入隐藏式包"))
        self.hidden_import_le.setPlaceholderText(_translate("add_data_widget", "多个包之间使用\";\"隔开"))
        self.hidden_import_lb.setText(_translate("add_data_widget", "包名"))
        self.additional_hook_gb.setTitle(_translate("add_data_widget", "Additional Hook"))
        self.additional_hook_le.setPlaceholderText(_translate("add_data_widget", "多个hook之间使用\';\'分隔"))
        self.additional_hook_lb.setText(_translate("add_data_widget", "路径："))
        self.runtime_hook_gb.setTitle(_translate("add_data_widget", "Runtime Hook"))
        self.runtime_hook_le.setPlaceholderText(_translate("add_data_widget", "多个hook之间使用\';\'分隔"))
        self.runtime_hook_lb.setText(_translate("add_data_widget", "路径："))
        self.exclude_module_gb.setTitle(_translate("add_data_widget", "排除包/模块"))
        self.exclude_module_le.setPlaceholderText(_translate("add_data_widget", "多个包之间使用\';\'分隔"))
        self.exclude_module_lb.setText(_translate("add_data_widget", "包名："))
        self.encrypt_gb.setTitle(_translate("add_data_widget", "加密"))
        self.encrypt_lb.setText(_translate("add_data_widget", "密钥"))
        self.encrypt_le.setPlaceholderText(_translate("add_data_widget", "请输入16个字节密钥"))
