# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\general_item_widget.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_general_item_widget(object):
    def setupUi(self, general_item_widget):
        general_item_widget.setObjectName("general_item_widget")
        general_item_widget.resize(600, 450)
        self.verticalLayout = QtWidgets.QVBoxLayout(general_item_widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 9)
        self.verticalLayout.setSpacing(9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dist_gb = QtWidgets.QGroupBox(general_item_widget)
        self.dist_gb.setCheckable(True)
        self.dist_gb.setChecked(False)
        self.dist_gb.setObjectName("dist_gb")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.dist_gb)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.dist_path_le = QtWidgets.QLineEdit(self.dist_gb)
        self.dist_path_le.setObjectName("dist_path_le")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dist_path_le)
        self.dist_path_str_lb = QtWidgets.QLabel(self.dist_gb)
        self.dist_path_str_lb.setObjectName("dist_path_str_lb")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.dist_path_str_lb)
        self.horizontalLayout.addLayout(self.formLayout)
        self.select_dist_path_pb = QtWidgets.QPushButton(self.dist_gb)
        self.select_dist_path_pb.setObjectName("select_dist_path_pb")
        self.horizontalLayout.addWidget(self.select_dist_path_pb)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.dist_gb)
        self.temp_work_path_gb = QtWidgets.QGroupBox(general_item_widget)
        self.temp_work_path_gb.setCheckable(True)
        self.temp_work_path_gb.setChecked(False)
        self.temp_work_path_gb.setObjectName("temp_work_path_gb")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.temp_work_path_gb)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.temp_work_path_le = QtWidgets.QLineEdit(self.temp_work_path_gb)
        self.temp_work_path_le.setObjectName("temp_work_path_le")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.temp_work_path_le)
        self.build_path_str_lb = QtWidgets.QLabel(self.temp_work_path_gb)
        self.build_path_str_lb.setObjectName("build_path_str_lb")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.build_path_str_lb)
        self.horizontalLayout_2.addLayout(self.formLayout_2)
        self.select_temp_work_path_pb = QtWidgets.QPushButton(self.temp_work_path_gb)
        self.select_temp_work_path_pb.setObjectName("select_temp_work_path_pb")
        self.horizontalLayout_2.addWidget(self.select_temp_work_path_pb)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.temp_work_path_gb)
        self.no_confirm_gb = QtWidgets.QGroupBox(general_item_widget)
        self.no_confirm_gb.setObjectName("no_confirm_gb")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.no_confirm_gb)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.need_confirm_rb = QtWidgets.QRadioButton(self.no_confirm_gb)
        self.need_confirm_rb.setChecked(True)
        self.need_confirm_rb.setObjectName("need_confirm_rb")
        self.horizontalLayout_3.addWidget(self.need_confirm_rb)
        self.no_confirm_rb = QtWidgets.QRadioButton(self.no_confirm_gb)
        self.no_confirm_rb.setObjectName("no_confirm_rb")
        self.horizontalLayout_3.addWidget(self.no_confirm_rb)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.no_confirm_gb)
        self.upx_search_path_gb = QtWidgets.QGroupBox(general_item_widget)
        self.upx_search_path_gb.setEnabled(True)
        self.upx_search_path_gb.setCheckable(True)
        self.upx_search_path_gb.setChecked(False)
        self.upx_search_path_gb.setObjectName("upx_search_path_gb")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.upx_search_path_gb)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.upx_search_path_le = QtWidgets.QLineEdit(self.upx_search_path_gb)
        self.upx_search_path_le.setObjectName("upx_search_path_le")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.upx_search_path_le)
        self.upx_search_path_str_lb = QtWidgets.QLabel(self.upx_search_path_gb)
        self.upx_search_path_str_lb.setObjectName("upx_search_path_str_lb")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.upx_search_path_str_lb)
        self.horizontalLayout_4.addLayout(self.formLayout_3)
        self.upx_search_path_pb = QtWidgets.QPushButton(self.upx_search_path_gb)
        self.upx_search_path_pb.setObjectName("upx_search_path_pb")
        self.horizontalLayout_4.addWidget(self.upx_search_path_pb)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout.addWidget(self.upx_search_path_gb)
        self.unicode_gb = QtWidgets.QGroupBox(general_item_widget)
        self.unicode_gb.setObjectName("unicode_gb")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.unicode_gb)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.unicode_support_rb = QtWidgets.QRadioButton(self.unicode_gb)
        self.unicode_support_rb.setChecked(True)
        self.unicode_support_rb.setObjectName("unicode_support_rb")
        self.horizontalLayout_5.addWidget(self.unicode_support_rb)
        self.unicode_not_support_rb = QtWidgets.QRadioButton(self.unicode_gb)
        self.unicode_not_support_rb.setObjectName("unicode_not_support_rb")
        self.horizontalLayout_5.addWidget(self.unicode_not_support_rb)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout.addWidget(self.unicode_gb)
        self.temp_file_gb = QtWidgets.QGroupBox(general_item_widget)
        self.temp_file_gb.setObjectName("temp_file_gb")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.temp_file_gb)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.clean_cache_cb = QtWidgets.QCheckBox(self.temp_file_gb)
        self.clean_cache_cb.setObjectName("clean_cache_cb")
        self.horizontalLayout_6.addWidget(self.clean_cache_cb)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.verticalLayout.addWidget(self.temp_file_gb)
        self.log_level_gb = QtWidgets.QGroupBox(general_item_widget)
        self.log_level_gb.setObjectName("log_level_gb")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.log_level_gb)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label = QtWidgets.QLabel(self.log_level_gb)
        self.label.setObjectName("label")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.log_level_cb = QtWidgets.QComboBox(self.log_level_gb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log_level_cb.sizePolicy().hasHeightForWidth())
        self.log_level_cb.setSizePolicy(sizePolicy)
        self.log_level_cb.setObjectName("log_level_cb")
        self.log_level_cb.addItem("")
        self.log_level_cb.addItem("")
        self.log_level_cb.addItem("")
        self.log_level_cb.addItem("")
        self.log_level_cb.addItem("")
        self.log_level_cb.addItem("")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.log_level_cb)
        self.horizontalLayout_7.addLayout(self.formLayout_4)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.verticalLayout.addWidget(self.log_level_gb)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)

        self.retranslateUi(general_item_widget)
        QtCore.QMetaObject.connectSlotsByName(general_item_widget)

    def retranslateUi(self, general_item_widget):
        _translate = QtCore.QCoreApplication.translate
        general_item_widget.setWindowTitle(_translate("general_item_widget", "Frame"))
        self.dist_gb.setTitle(_translate("general_item_widget", "打包好的app放置目录"))
        self.dist_path_le.setToolTip(_translate("general_item_widget", "打包的应用程序放在哪里(默认:./dist)"))
        self.dist_path_le.setPlaceholderText(_translate("general_item_widget", "默认:./dist"))
        self.dist_path_str_lb.setText(_translate("general_item_widget", "路径:"))
        self.select_dist_path_pb.setText(_translate("general_item_widget", "选择目录"))
        self.temp_work_path_gb.setTitle(_translate("general_item_widget", "临时工作目录"))
        self.temp_work_path_le.setToolTip(_translate("general_item_widget", "所有临时工作文件，.log，.pyz等存放位置(默认: ./build)"))
        self.temp_work_path_le.setPlaceholderText(_translate("general_item_widget", "默认: ./build"))
        self.build_path_str_lb.setText(_translate("general_item_widget", "路径:"))
        self.select_temp_work_path_pb.setText(_translate("general_item_widget", "选择目录"))
        self.no_confirm_gb.setToolTip(_translate("general_item_widget", "默认: SPECPATH/dist/SPECNAME"))
        self.no_confirm_gb.setTitle(_translate("general_item_widget", "替换输出目录"))
        self.need_confirm_rb.setToolTip(_translate("general_item_widget", "提示原有目录存在，停止打包"))
        self.need_confirm_rb.setText(_translate("general_item_widget", "需要提示"))
        self.no_confirm_rb.setToolTip(_translate("general_item_widget", "直接删除原有打包目录"))
        self.no_confirm_rb.setText(_translate("general_item_widget", "不需要提示"))
        self.upx_search_path_gb.setToolTip(_translate("general_item_widget", "UPX实用程序的路径(默认:搜索执行路径)"))
        self.upx_search_path_gb.setTitle(_translate("general_item_widget", "设置UPX搜索路径"))
        self.upx_search_path_le.setPlaceholderText(_translate("general_item_widget", "默认:搜索执行路径"))
        self.upx_search_path_str_lb.setText(_translate("general_item_widget", "路径:"))
        self.upx_search_path_pb.setText(_translate("general_item_widget", "选择目录"))
        self.unicode_gb.setToolTip(_translate("general_item_widget", "不包含unicode编码支持(默认:如果可用就包含)"))
        self.unicode_gb.setTitle(_translate("general_item_widget", "unicode编码"))
        self.unicode_support_rb.setText(_translate("general_item_widget", "有就包含"))
        self.unicode_not_support_rb.setText(_translate("general_item_widget", "不包含支持"))
        self.temp_file_gb.setToolTip(_translate("general_item_widget", "在构建之前清理PyInstaller缓存并删除临时文件"))
        self.temp_file_gb.setTitle(_translate("general_item_widget", "临时文件"))
        self.clean_cache_cb.setText(_translate("general_item_widget", "打包前清理"))
        self.log_level_gb.setToolTip(_translate("general_item_widget", "构建时控制台消息中的详细信息"))
        self.log_level_gb.setTitle(_translate("general_item_widget", "打包时控制台消息"))
        self.label.setText(_translate("general_item_widget", "级别:"))
        self.log_level_cb.setItemText(0, _translate("general_item_widget", "TRACE"))
        self.log_level_cb.setItemText(1, _translate("general_item_widget", "DEBUG"))
        self.log_level_cb.setItemText(2, _translate("general_item_widget", "INFO"))
        self.log_level_cb.setItemText(3, _translate("general_item_widget", "WARN"))
        self.log_level_cb.setItemText(4, _translate("general_item_widget", "ERROR"))
        self.log_level_cb.setItemText(5, _translate("general_item_widget", "CRITICAL"))
