# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\left_menu_widget.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pyinstaller_gui(object):
    def setupUi(self, pyinstaller_gui):
        pyinstaller_gui.setObjectName("pyinstaller_gui")
        pyinstaller_gui.resize(504, 417)
        self.horizontalLayout = QtWidgets.QHBoxLayout(pyinstaller_gui)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.left_menu_frame = QtWidgets.QFrame(pyinstaller_gui)
        self.left_menu_frame.setAutoFillBackground(False)
        self.left_menu_frame.setStyleSheet("")
        self.left_menu_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_menu_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_menu_frame.setObjectName("left_menu_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.left_menu_frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.general_item_tb = QtWidgets.QToolButton(self.left_menu_frame)
        self.general_item_tb.setAutoFillBackground(True)
        self.general_item_tb.setStyleSheet("width:100 px;\n"
"height: 30 px;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/left_menu/general.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.general_item_tb.setIcon(icon)
        self.general_item_tb.setCheckable(True)
        self.general_item_tb.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.general_item_tb.setAutoRaise(True)
        self.general_item_tb.setObjectName("general_item_tb")
        self.verticalLayout_3.addWidget(self.general_item_tb)
        self.add_data_item_tb = QtWidgets.QToolButton(self.left_menu_frame)
        self.add_data_item_tb.setAutoFillBackground(True)
        self.add_data_item_tb.setStyleSheet("width:100 px;\n"
"height: 30 px;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/left_menu/packet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_data_item_tb.setIcon(icon1)
        self.add_data_item_tb.setCheckable(True)
        self.add_data_item_tb.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.add_data_item_tb.setAutoRaise(True)
        self.add_data_item_tb.setObjectName("add_data_item_tb")
        self.verticalLayout_3.addWidget(self.add_data_item_tb)
        self.system_spec_item_tb = QtWidgets.QToolButton(self.left_menu_frame)
        self.system_spec_item_tb.setAutoFillBackground(True)
        self.system_spec_item_tb.setStyleSheet("width:100 px;\n"
"height: 30 px;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/left_menu/about_system.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.system_spec_item_tb.setIcon(icon2)
        self.system_spec_item_tb.setCheckable(True)
        self.system_spec_item_tb.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.system_spec_item_tb.setAutoRaise(True)
        self.system_spec_item_tb.setObjectName("system_spec_item_tb")
        self.verticalLayout_3.addWidget(self.system_spec_item_tb)
        self.generate_item_tb = QtWidgets.QToolButton(self.left_menu_frame)
        self.generate_item_tb.setAutoFillBackground(True)
        self.generate_item_tb.setStyleSheet("width:100 px;\n"
"height: 30 px;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/left_menu/about_file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.generate_item_tb.setIcon(icon3)
        self.generate_item_tb.setCheckable(True)
        self.generate_item_tb.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.generate_item_tb.setAutoRaise(True)
        self.generate_item_tb.setObjectName("generate_item_tb")
        self.verticalLayout_3.addWidget(self.generate_item_tb)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 28, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.start_build_pb = QtWidgets.QPushButton(self.left_menu_frame)
        self.start_build_pb.setMinimumSize(QtCore.QSize(60, 60))
        self.start_build_pb.setMaximumSize(QtCore.QSize(60, 60))
        self.start_build_pb.setAutoFillBackground(True)
        self.start_build_pb.setCheckable(True)
        self.start_build_pb.setObjectName("start_build_pb")
        self.horizontalLayout_2.addWidget(self.start_build_pb)
        spacerItem1 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.left_menu_frame)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.item_widget_hl = QtWidgets.QVBoxLayout()
        self.item_widget_hl.setContentsMargins(6, 6, 6, -1)
        self.item_widget_hl.setObjectName("item_widget_hl")
        self.right_scroll_area = QtWidgets.QScrollArea(pyinstaller_gui)
        self.right_scroll_area.setWidgetResizable(True)
        self.right_scroll_area.setObjectName("right_scroll_area")
        self.right_scroll_widget = QtWidgets.QWidget()
        self.right_scroll_widget.setGeometry(QtCore.QRect(0, 0, 379, 408))
        self.right_scroll_widget.setObjectName("right_scroll_widget")
        self.scroll_area_vl = QtWidgets.QVBoxLayout(self.right_scroll_widget)
        self.scroll_area_vl.setContentsMargins(0, 0, 0, 0)
        self.scroll_area_vl.setObjectName("scroll_area_vl")
        self.right_scroll_area.setWidget(self.right_scroll_widget)
        self.item_widget_hl.addWidget(self.right_scroll_area)
        self.horizontalLayout.addLayout(self.item_widget_hl)
        self.horizontalLayout.setStretch(1, 1)

        self.retranslateUi(pyinstaller_gui)
        QtCore.QMetaObject.connectSlotsByName(pyinstaller_gui)

    def retranslateUi(self, pyinstaller_gui):
        _translate = QtCore.QCoreApplication.translate
        pyinstaller_gui.setWindowTitle(_translate("pyinstaller_gui", "Form"))
        self.general_item_tb.setText(_translate("pyinstaller_gui", " 通用选项"))
        self.add_data_item_tb.setText(_translate("pyinstaller_gui", " 添加文件"))
        self.system_spec_item_tb.setText(_translate("pyinstaller_gui", " 系统特定参数"))
        self.generate_item_tb.setText(_translate("pyinstaller_gui", " 打包生成"))
        self.start_build_pb.setText(_translate("pyinstaller_gui", "开始构建"))
import resource.resource_rc
