# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\version_file.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_file_version_desc_widget(object):
    def setupUi(self, file_version_desc_widget):
        file_version_desc_widget.setObjectName("file_version_desc_widget")
        file_version_desc_widget.resize(555, 458)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/left_menu/app_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        file_version_desc_widget.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(file_version_desc_widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.file_version_tree = QtWidgets.QTreeWidget(file_version_desc_widget)
        self.file_version_tree.setAlternatingRowColors(True)
        self.file_version_tree.setAnimated(True)
        self.file_version_tree.setObjectName("file_version_tree")
        item_0 = QtWidgets.QTreeWidgetItem(self.file_version_tree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        self.file_version_tree.header().setCascadingSectionResizes(False)
        self.file_version_tree.header().setDefaultSectionSize(220)
        self.file_version_tree.header().setHighlightSections(True)
        self.verticalLayout.addWidget(self.file_version_tree)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 9, 9)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.ok_pb = QtWidgets.QPushButton(file_version_desc_widget)
        self.ok_pb.setObjectName("ok_pb")
        self.horizontalLayout.addWidget(self.ok_pb)
        self.cancel_pb = QtWidgets.QPushButton(file_version_desc_widget)
        self.cancel_pb.setObjectName("cancel_pb")
        self.horizontalLayout.addWidget(self.cancel_pb)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(file_version_desc_widget)
        QtCore.QMetaObject.connectSlotsByName(file_version_desc_widget)

    def retranslateUi(self, file_version_desc_widget):
        _translate = QtCore.QCoreApplication.translate
        file_version_desc_widget.setWindowTitle(_translate("file_version_desc_widget", "版本文件[*]"))
        self.file_version_tree.headerItem().setText(0, _translate("file_version_desc_widget", "属性"))
        self.file_version_tree.headerItem().setText(1, _translate("file_version_desc_widget", "值"))
        __sortingEnabled = self.file_version_tree.isSortingEnabled()
        self.file_version_tree.setSortingEnabled(False)
        self.file_version_tree.topLevelItem(0).setText(0, _translate("file_version_desc_widget", "VSVersionInfo"))
        self.file_version_tree.topLevelItem(0).child(0).setText(0, _translate("file_version_desc_widget", "FixedFileInfo"))
        self.file_version_tree.topLevelItem(0).child(0).child(0).setText(0, _translate("file_version_desc_widget", "File Version"))
        self.file_version_tree.topLevelItem(0).child(0).child(0).child(0).setText(0, _translate("file_version_desc_widget", "1"))
        self.file_version_tree.topLevelItem(0).child(0).child(0).child(1).setText(0, _translate("file_version_desc_widget", "2"))
        self.file_version_tree.topLevelItem(0).child(0).child(0).child(2).setText(0, _translate("file_version_desc_widget", "3"))
        self.file_version_tree.topLevelItem(0).child(0).child(0).child(3).setText(0, _translate("file_version_desc_widget", "4"))
        self.file_version_tree.topLevelItem(0).child(0).child(1).setText(0, _translate("file_version_desc_widget", "Product Version"))
        self.file_version_tree.topLevelItem(0).child(0).child(1).child(0).setText(0, _translate("file_version_desc_widget", "1"))
        self.file_version_tree.topLevelItem(0).child(0).child(1).child(1).setText(0, _translate("file_version_desc_widget", "2"))
        self.file_version_tree.topLevelItem(0).child(0).child(1).child(2).setText(0, _translate("file_version_desc_widget", "3"))
        self.file_version_tree.topLevelItem(0).child(0).child(1).child(3).setText(0, _translate("file_version_desc_widget", "4"))
        self.file_version_tree.topLevelItem(0).child(0).child(2).setText(0, _translate("file_version_desc_widget", "File Type"))
        self.file_version_tree.topLevelItem(0).child(0).child(2).setText(1, _translate("file_version_desc_widget", "0x01"))
        self.file_version_tree.topLevelItem(0).child(1).setText(0, _translate("file_version_desc_widget", "kids"))
        self.file_version_tree.topLevelItem(0).child(1).child(0).setText(0, _translate("file_version_desc_widget", "StringFileInfo"))
        self.file_version_tree.topLevelItem(0).child(1).child(0).child(0).setText(0, _translate("file_version_desc_widget", "StringTable"))
        self.file_version_tree.topLevelItem(0).child(1).child(0).child(0).child(0).setText(0, _translate("file_version_desc_widget", "CompanyName"))
        self.file_version_tree.topLevelItem(0).child(1).child(0).child(0).child(1).setText(0, _translate("file_version_desc_widget", "FileDescription"))
        self.file_version_tree.topLevelItem(0).child(1).child(0).child(0).child(2).setText(0, _translate("file_version_desc_widget", "FileVersion"))
        self.file_version_tree.topLevelItem(0).child(1).child(0).child(0).child(3).setText(0, _translate("file_version_desc_widget", "InternalName"))
        self.file_version_tree.topLevelItem(0).child(1).child(0).child(0).child(4).setText(0, _translate("file_version_desc_widget", "LegalCopyright"))
        self.file_version_tree.topLevelItem(0).child(1).child(0).child(0).child(5).setText(0, _translate("file_version_desc_widget", "LegalTrademarks"))
        self.file_version_tree.topLevelItem(0).child(1).child(0).child(0).child(6).setText(0, _translate("file_version_desc_widget", "OriginalFilename"))
        self.file_version_tree.topLevelItem(0).child(1).child(0).child(0).child(7).setText(0, _translate("file_version_desc_widget", "ProductName"))
        self.file_version_tree.topLevelItem(0).child(1).child(0).child(0).child(8).setText(0, _translate("file_version_desc_widget", "ProductVersion"))
        self.file_version_tree.topLevelItem(0).child(1).child(1).setText(0, _translate("file_version_desc_widget", "VarFileInfo"))
        self.file_version_tree.topLevelItem(0).child(1).child(1).child(0).setText(0, _translate("file_version_desc_widget", "Translation"))
        self.file_version_tree.setSortingEnabled(__sortingEnabled)
        self.ok_pb.setText(_translate("file_version_desc_widget", "确认"))
        self.cancel_pb.setText(_translate("file_version_desc_widget", "取消"))
import resource.resource_rc
